version: '3'
services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/log/:/var/log/nginx/
      - /var/www/html:/var/www/html
    working_dir: /etc/nginx/conf.d
    environment:
      TZ: 'Asia/Shanghai'
    restart: always
    networks:
      - backend
      - frontend

  node:
    image: node:12.18.3
    hostname: node
    container_name: node
    ports:
      - "8080:8080"
    volumes:
      - /var/www/html:/var/www/html
    restart: always
    command: tail -f
    working_dir: /var/www/html
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - frontend

  php73:
    hostname: php73
    build: ./supervisor
    container_name: php73
    ports:
      - "9000:9000"
    volumes:
      - /var/www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/conf.d:/etc/supervisor/conf.d
      - ./supervisor/log:/var/log/supervisor
    working_dir: /var/www/html
    restart: always
    command: >
        bash -c "supervisord -s -c /etc/supervisor/supervisord.conf && php-fpm"
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend      
  
  php8:
    build: ./php8
    container_name: php8
    hostname: php8
    expose:
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/conf.d:/etc/supervisor/conf.d
      - ./supervisor/log:/var/log/supervisor
    working_dir: /var/www/html
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend

  php74:
    build: ./php74
    container_name: php74
    hostname: php74
    expose:
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/conf.d:/etc/supervisor/conf.d
      - ./supervisor/log:/var/log/supervisor
    working_dir: /var/www/html
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - backend

  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: elasticsearch:6.8.23
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      TZ: 'Asia/Shanghai'
      discovery.type: single-node # 单机版需要
      # ELASTIC_PASSWORD: '123456'
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch:z
    networks:
      - backend
    restart: always

  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./redis/redis.log:/usr/local/redis/redis.log    
      - ./redis/conf:/usr/local/etc/redis
    environment:
      TZ: 'Asia/Shanghai'
    # command: >
    #      --requirepass
    restart: always
    networks:
      - backend

  memcached:
    hostname: memcached
    container_name: memcached
    image: memcached
    expose:
      - "11211"
    restart: always
    networks:
      - backend

  rabbitmq1:
    hostname: rabbitmq1
    container_name: rabbitmq1
    image: rabbitmq:3.8-management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:      
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      TZ: 'Asia/Shanghai'
      RABBITMQ_ERLANG_COOKIE: 'rabbitmqCookie'
    restart: always
    networks:
      - backend

  rabbitmq2:
    hostname: rabbitmq2
    container_name: rabbitmq2
    image: rabbitmq:3.8-management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    ports:
      - "5673:5672"
    volumes:
      - ./rabbitmq/data2:/var/lib/rabbitmq
    environment:
      TZ: 'Asia/Shanghai'
      RABBITMQ_ERLANG_COOKIE: 'rabbitmqCookie'
    restart: always
    networks:
      - backend

  rabbitmq3:
    hostname: rabbitmq3
    container_name: rabbitmq3
    image: rabbitmq:3.8-management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    ports:
      - "5674:5672"
    volumes:
      - ./rabbitmq/data3:/var/lib/rabbitmq
    environment:
      TZ: 'Asia/Shanghai'
      RABBITMQ_ERLANG_COOKIE: 'rabbitmqCookie'
    restart: always
    networks:
      - backend    

networks:
  frontend:
  backend:



