version: '3'
services:
  nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log/:/var/log/nginx/
      - /var/www/:/var/www
    environment:
      TZ: 'Asia/Shanghai'
    restart: always
    networks:
      - backend
      - frontend

  phpfpm:
    image: php:8.0-fpm
    container_name: my_php
    ports:
      - "9000:9000"
    volumes:
      - /var/www/:/var/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lig/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    restart: always
    container_name: mysql

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/usr/local/redis/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./redis/redis.log:/usr/local/redis/redis.log    
      - ./redis/conf:/usr/local/etc/redis
    environment:
      TZ: 'Asia/Shanghai'
    restart: always
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:      
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      TZ: 'Asia/Shanghai'
    networks:
      - backend
    restart: always

networks:
  frontend:
  backend:



