version: '3'
services:
  nginx:
    image: nginx
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
       - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
       - ./nginx/log/:/var/log/nginx/
       - /var/www/:/var/www
    restart: always
    networks:
      - backend
      - frontend

  phpfpm:
    image: php:7.3-fpm
    container_name: my_php
    ports:
       - "9000:9000"
    volumes:
        - /var/www/:/var/www/
        - ./php/php.ini:/usr/local/php/etc/php.ini
        - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
        - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        - ./php/log/:/usr/local/php/var/log/
    restart: always
    networks:
      - backend
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lig/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - backend
    restart: always
    container_name: mysql

networks:
  frontend:
  backend:

