version: '3'
services:
  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/log/:/var/log/nginx/
      - /var/www/html:/var/www/html
    working_dir: /etc/nginx/conf.d
    environment:
      TZ: 'Asia/Shanghai'
    restart: always
    networks:
      - backend
      - frontend

  node:
    image: node
    hostname: node
    container_name: node
    volumes:
      - /var/www/html:/var/www/html
    restart: always
    command: tail -f
    working_dir: /var/www/html
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - frontend

  php73:
    hostname: php73
    build: ./php
    container_name: php73
    ports:
      - "9000:9000"
    volumes:
      - /var/www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
    working_dir: /var/www/html
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend

  supervisor:
    hostname: supervisor
    build: ./supervisor
    container_name: supervisor
    expose:
      - "9000"
    volumes:
      - ./supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./supervisor/conf.d:/etc/supervisor/conf.d
      - ./supervisor/log:/var/log/supervisor
      - /var/www/html:/var/www/html
    working_dir: /etc/supervisor/conf.d
    restart: always
    command: >
      bash -c "supervisord -s -c /etc/supervisor/supervisord.conf && php-fpm"
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend
  
  php8:
    build: ./php8
    container_name: php8
    hostname: php8
    expose:
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
    working_dir: /var/www/html
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend

  php74:
    build: ./php74
    container_name: php74
    hostname: php74
    expose:
      - "9000"
    volumes:
      - /var/www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/log/:/usr/local/php/var/log/
    working_dir: /var/www/html
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - backend

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - backend

  elasticsearch:
    hostname: elasticsearch
    container_name: elasticsearch
    image: elasticsearch:7.16.2
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      TZ: 'Asia/Shanghai'
      # ELASTIC_PASSWORD: '123456'
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:z
    networks:
      - backend
    restart: always

  Logstash:
    hostname: logstash
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    # volumes:
    #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
    #  - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - backend

  Kibana:
    hostname: kibana
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    privileged: true
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    # volumes:
    #  - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - backend


  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./redis/redis.log:/usr/local/redis/redis.log    
      - ./redis/conf:/usr/local/etc/redis
    environment:
      TZ: 'Asia/Shanghai'
    # command: >
    #      --requirepass
    restart: always
    networks:
      - backend

  memcached:
    hostname: memcached
    container_name: memcached
    image: memcached
    expose:
      - "11211"
    restart: always
    networks:
      - backend

  rabbitmq1:
    hostname: rabbitmq1
    container_name: rabbitmq1
    image: rabbitmq:3.8-management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    environment:      
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
      TZ: 'Asia/Shanghai'
      RABBITMQ_ERLANG_COOKIE: 'rabbitmqCookie'
    restart: always
    networks:
      - backend

  rabbitmq2:
    hostname: rabbitmq2
    container_name: rabbitmq2
    image: rabbitmq:3.8-management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    ports:
      - "5673:5672"
    volumes:
      - ./rabbitmq/data2:/var/lib/rabbitmq
    environment:
      TZ: 'Asia/Shanghai'
      RABBITMQ_ERLANG_COOKIE: 'rabbitmqCookie'
    restart: always
    networks:
      - backend

  rabbitmq3:
    hostname: rabbitmq3
    container_name: rabbitmq3
    image: rabbitmq:3.8-management
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G      
    ports:
      - "5674:5672"
    volumes:
      - ./rabbitmq/data3:/var/lib/rabbitmq
    environment:
      TZ: 'Asia/Shanghai'
      RABBITMQ_ERLANG_COOKIE: 'rabbitmqCookie'
    restart: always
    networks:
      - backend

  golang:
    hostname: golang
    container_name: golang
    build:
      context: ./golang
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - memcached
      - redis
      - mysql
      - nginx
    volumes:
      - /var/www/html:/app
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: 2G
    # command: go run ./golang/main.go
    working_dir: /app
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - frontend

networks:
  frontend:
  backend:



